/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import visao.TelaDeVeiculo;
import visao.TelaMarca;
import visao.TelaProprietario;

/**
 *
 * @author Note
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        jButtonCadastrarProprietario.setFocusPainted(false); // Oculta a aparência de seleção do botão
        jButtonCadastrarMarca.setFocusPainted(false); // Oculta a aparência de seleção do botão
        jButtonCadastrarModelo.setFocusPainted(false); // Oculta a aparência de seleção do botão
        jButtonCadastrarVeiculo.setFocusPainted(false); // Oculta a aparência de seleção do botão
        jButtonGastosVeiculares.setFocusPainted(false); // Oculta a aparência de seleção do botão

        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonCadastrarMarca = new javax.swing.JButton();
        jButtonCadastrarModelo = new javax.swing.JButton();
        jButtonCadastrarVeiculo = new javax.swing.JButton();
        jButtonGastosVeiculares = new javax.swing.JButton();
        jButtonCadastrarProprietario = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonGastosVeiculares1 = new javax.swing.JButton();
        jButtonGastosVeiculares2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(182, 202, 221));
        jPanel1.setForeground(new java.awt.Color(182, 202, 221));
        jPanel1.setMaximumSize(new java.awt.Dimension(1440, 900));
        jPanel1.setMinimumSize(new java.awt.Dimension(1440, 900));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(33, 43, 70));
        jLabel2.setText("SISTEMA DE CONTROLE DE GASTOS");

        jPanel2.setBackground(new java.awt.Color(60, 95, 143));
        jPanel2.setForeground(new java.awt.Color(60, 95, 143));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 42, 70));
        jLabel1.setText("MENU");

        jButtonCadastrarMarca.setBackground(new java.awt.Color(92, 116, 123));
        jButtonCadastrarMarca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCadastrarMarca.setText("CADASTRAR MARCA");
        jButtonCadastrarMarca.setBorder(null);
        jButtonCadastrarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarMarcaActionPerformed(evt);
            }
        });

        jButtonCadastrarModelo.setBackground(new java.awt.Color(92, 116, 123));
        jButtonCadastrarModelo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCadastrarModelo.setText("CADASTRAR MODELO");
        jButtonCadastrarModelo.setBorder(null);
        jButtonCadastrarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarModeloActionPerformed(evt);
            }
        });

        jButtonCadastrarVeiculo.setBackground(new java.awt.Color(92, 116, 123));
        jButtonCadastrarVeiculo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCadastrarVeiculo.setText("CADASTRAR VEÍCULO");
        jButtonCadastrarVeiculo.setBorder(null);
        jButtonCadastrarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarVeiculoActionPerformed(evt);
            }
        });

        jButtonGastosVeiculares.setBackground(new java.awt.Color(92, 116, 123));
        jButtonGastosVeiculares.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonGastosVeiculares.setText("CADASTRAR CATEGORIA DE GASTOS");
        jButtonGastosVeiculares.setBorder(null);
        jButtonGastosVeiculares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGastosVeicularesActionPerformed(evt);
            }
        });

        jButtonCadastrarProprietario.setBackground(new java.awt.Color(92, 116, 123));
        jButtonCadastrarProprietario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCadastrarProprietario.setText("CADASTRAR PROPRIETÁRIO");
        jButtonCadastrarProprietario.setBorder(null);
        jButtonCadastrarProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarProprietarioActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LogoCarro.png"))); // NOI18N

        jButtonGastosVeiculares1.setBackground(new java.awt.Color(92, 116, 123));
        jButtonGastosVeiculares1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonGastosVeiculares1.setText("CADASTRAR GASTOS");
        jButtonGastosVeiculares1.setBorder(null);
        jButtonGastosVeiculares1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGastosVeiculares1ActionPerformed(evt);
            }
        });

        jButtonGastosVeiculares2.setBackground(new java.awt.Color(92, 116, 123));
        jButtonGastosVeiculares2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonGastosVeiculares2.setText("EMITIR RELATÓRIO");
        jButtonGastosVeiculares2.setBorder(null);
        jButtonGastosVeiculares2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGastosVeiculares2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCadastrarMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCadastrarModelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCadastrarVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonGastosVeiculares, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCadastrarProprietario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonGastosVeiculares1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonGastosVeiculares2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCadastrarProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButtonCadastrarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCadastrarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCadastrarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGastosVeiculares, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGastosVeiculares1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGastosVeiculares2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(239, 239, 239))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarProprietarioActionPerformed

        TelaProprietario telaProprietario = new TelaProprietario();
        // Fechar a janela atual
        dispose();

        // Exibir a nova JFrame
        telaProprietario.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarProprietarioActionPerformed

    private void jButtonCadastrarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarMarcaActionPerformed

        TelaMarca telaMarca = new TelaMarca();
        // Fechar a janela atual
        dispose();

        // Exibir a nova JFrame
        telaMarca.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarMarcaActionPerformed

    private void jButtonCadastrarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarModeloActionPerformed

        try {
            TelaDeModelo telaDeModelo = new TelaDeModelo();
            // Fechar a janela atual
            dispose();

            // Exibir a nova JFrame
            telaDeModelo.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCadastrarModeloActionPerformed

    private void jButtonCadastrarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarVeiculoActionPerformed

        TelaDeVeiculo telaDeVeiculo = new TelaDeVeiculo();
        // Fechar a janela atual
        dispose();

        // Exibir a nova JFrame
        telaDeVeiculo.setVisible(true);

    }//GEN-LAST:event_jButtonCadastrarVeiculoActionPerformed

    private void jButtonGastosVeicularesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGastosVeicularesActionPerformed
        TelaCategoriaGastos telaCategoriaGastos = new TelaCategoriaGastos();
        // Fechar a janela atual
        dispose();

        // Exibir a nova JFrame
        telaCategoriaGastos.setVisible(true);
    }//GEN-LAST:event_jButtonGastosVeicularesActionPerformed

    private void jButtonGastosVeiculares1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGastosVeiculares1ActionPerformed
        TelaGastos telaGastos = new TelaGastos();
        // Fechar a janela atual
        dispose();

        // Exibir a nova JFrame
        telaGastos.setVisible(true);
    }//GEN-LAST:event_jButtonGastosVeiculares1ActionPerformed

    private void jButtonGastosVeiculares2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGastosVeiculares2ActionPerformed
        TelaRelatorio telaRelatorio = new TelaRelatorio();
        // Fechar a janela atual
        dispose();

        // Exibir a nova JFrame
        telaRelatorio.setVisible(true);
    }//GEN-LAST:event_jButtonGastosVeiculares2ActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarMarca;
    private javax.swing.JButton jButtonCadastrarModelo;
    private javax.swing.JButton jButtonCadastrarProprietario;
    private javax.swing.JButton jButtonCadastrarVeiculo;
    private javax.swing.JButton jButtonGastosVeiculares;
    private javax.swing.JButton jButtonGastosVeiculares1;
    private javax.swing.JButton jButtonGastosVeiculares2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
